#!/usr/bin/env bash
set -euo pipefail

# create-release-pr.sh — Update VERSION, prepend changelog, commit and push.
# If on a non-main branch with an existing PR, pushes to that branch.
# If on main, creates a release branch and PR.
# Usage: create-release-pr.sh <new-version> <changelog-section-file>

REPO="${GITHUB_REPOSITORY:-Codagent-AI/agent-runner}"
VERSION_FILE="VERSION"
CHANGELOG="CHANGELOG.md"

NEW_VERSION="${1:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"
CHANGELOG_FILE="${2:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"

if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Error: invalid version: $NEW_VERSION" >&2
  exit 1
fi

if [ ! -f "$CHANGELOG_FILE" ]; then
  echo "Error: changelog section file not found: $CHANGELOG_FILE" >&2
  exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)

if [ "$CURRENT_BRANCH" = "main" ]; then
  git checkout -q -B "release/v${NEW_VERSION}"
fi

printf '%s\n' "$NEW_VERSION" > "$VERSION_FILE"

if [ -f "$CHANGELOG" ]; then
  {
    head -1 "$CHANGELOG"
    echo ""
    cat "$CHANGELOG_FILE"
    tail -n +2 "$CHANGELOG"
  } > "${CHANGELOG}.tmp" && mv "${CHANGELOG}.tmp" "$CHANGELOG"
else
  {
    echo "# agent-runner"
    echo ""
    cat "$CHANGELOG_FILE"
  } > "$CHANGELOG"
fi

git add "$VERSION_FILE" "$CHANGELOG"
git commit -q -m "chore: release v${NEW_VERSION}"

if [ "$CURRENT_BRANCH" = "main" ]; then
  git push -q -u origin "release/v${NEW_VERSION}"
  gh pr create --repo "$REPO" --base main \
    --title "chore: release v${NEW_VERSION}" \
    --body "$(cat <<EOF
## Release v${NEW_VERSION}

This PR was generated by the \`/release\` skill.

When merged, the release workflow will publish the explicit version in \`VERSION\`.
EOF
)"
else
  git push -q
  gh pr view "$CURRENT_BRANCH" --repo "$REPO" --json url --jq .url
fi
