package runview

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/mattn/go-runewidth"

	"github.com/codagent/agent-runner/internal/tuistyle"
)

// ---- Block renderers ---------------------------------------------------------
// Each renderXxxBlock function returns the lines of one block (without the
// 2*indent prefix — buildLogLines prepends that). The first line is always a
// separator generated by renderSeparator; remaining lines are content.

func renderShellBlock(node *StepNode, indent, width int, loadedFull bool) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	glyph := blockTypeGlyph(node.Type)
	sep := renderSeparator(node.ID, glyph, indent, contentWidth)

	var lines []string
	lines = append(lines, sep)

	cmd := node.InterpolatedCommand
	if cmd == "" {
		cmd = node.StaticCommand
	}
	if cmd != "" {
		lines = append(lines, renderWrappedText("$ "+cmd, contentWidth)...)
		lines = append(lines, "")
	}

	lines = append(lines, blockCommonModifiers(node)...)

	if node.Status == StatusPending {
		return lines
	}

	lines = append(lines, blockExitAndDuration(node)...)

	if node.ErrorMessage != "" {
		lines = append(lines, "", blockLabelStr("error:"))
		lines = append(lines, renderWrappedText(node.ErrorMessage, contentWidth)...)
		return lines
	}

	lines = append(lines, renderOutputSection("stdout", node.Stdout, contentWidth, loadedFull)...)
	lines = append(lines, renderOutputSection("stderr", node.Stderr, contentWidth, loadedFull)...)
	return lines
}

// blockAgentHeader appends the shared agent metadata lines (profile, model,
// cli, session, prompt) that are identical for headless and interactive blocks.
func blockAgentHeader(node *StepNode, contentWidth int) []string {
	var lines []string
	profile := node.AgentProfile
	if profile == "" {
		profile = node.StaticAgent
	}
	if profile != "" {
		lines = append(lines, blockDimStr("agent", profile))
	}
	mdl := node.AgentModel
	if mdl == "" {
		mdl = node.StaticModel
	}
	if mdl != "" {
		lines = append(lines, blockDimStr("model", mdl))
	}
	cli := node.AgentCLI
	if cli == "" {
		cli = node.StaticCLI
	}
	if cli != "" {
		lines = append(lines, blockDimStr("cli", cli))
	}
	if node.StaticSession != "" {
		lines = append(lines, blockDimStr("session", string(node.StaticSession)))
	}
	if node.SessionID != "" {
		lines = append(lines, blockDimStr("session id", node.SessionID))
	}
	lines = append(lines, blockCommonModifiers(node)...)
	prompt := node.InterpolatedPrompt
	if prompt == "" {
		prompt = node.StaticPrompt
	}
	prompt = strings.TrimRight(prompt, "\r\n")
	if prompt != "" {
		lines = append(lines, "", blockLabelStr("prompt:"))
		lines = append(lines, renderWrappedText(prompt, contentWidth)...)
	}
	return lines
}

func renderHeadlessBlock(node *StepNode, indent, width int, loadedFull bool, pulsePhase float64, running bool) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	lines := []string{renderSeparator(node.ID, blockTypeGlyph(node.Type), indent, contentWidth)}
	lines = append(lines, blockAgentHeader(node, contentWidth)...)

	if node.Status == StatusPending {
		return lines
	}

	lines = append(lines, blockExitAndDuration(node)...)

	if node.ErrorMessage != "" {
		lines = append(lines, "", blockLabelStr("error:"))
		lines = append(lines, renderWrappedText(node.ErrorMessage, contentWidth)...)
		return lines
	}

	lines = append(lines, renderAgentOutput(node, contentWidth, loadedFull, pulsePhase)...)

	if node.SessionID != "" && !running {
		lines = append(lines, "", tuistyle.AccentStyle.Render("enter → resume session"))
	}
	return lines
}

func renderInteractiveBlock(node *StepNode, indent, width int, running bool) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	lines := []string{renderSeparator(node.ID, blockTypeGlyph(node.Type), indent, contentWidth)}
	lines = append(lines, blockAgentHeader(node, contentWidth)...)

	if node.Status == StatusPending {
		return lines
	}

	lines = append(lines, blockOutcomeAndDuration(node)...)

	if node.ErrorMessage != "" {
		lines = append(lines, "", blockLabelStr("error:"))
		lines = append(lines, renderWrappedText(node.ErrorMessage, contentWidth)...)
	}

	if node.SessionID != "" && !running {
		lines = append(lines, "", tuistyle.AccentStyle.Render("enter → resume session"))
	}
	return lines
}

func renderSubWorkflowBlock(node *StepNode, indent, width int, resolverCfg ResolverConfig) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	glyph := blockTypeGlyph(node.Type)
	sep := renderSeparator(node.ID, glyph, indent, contentWidth)

	var lines []string
	lines = append(lines, sep)

	name := CanonicalName(node.StaticWorkflowPath, resolverCfg)
	if name == "" {
		name = bareWorkflowName(node.StaticWorkflow)
	}
	if name != "" {
		lines = append(lines, blockDimStr("workflow", name))
	}

	params := node.InterpolatedParams
	if params == nil {
		params = node.StaticParams
	}
	lines = append(lines, sortedParams(params)...)

	lines = append(lines, blockCommonModifiers(node)...)

	if node.Status != StatusPending {
		lines = append(lines, blockOutcomeAndDuration(node)...)
	}
	return lines
}

func renderLoopBlock(node *StepNode, indent, width int) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	glyph := blockTypeGlyph(node.Type)
	sep := renderSeparator(node.ID, glyph, indent, contentWidth)

	var lines []string
	lines = append(lines, sep)

	loopType := node.LoopType
	if loopType == "" {
		if node.StaticLoopOver != "" {
			loopType = "for-each"
		} else {
			loopType = "counted"
		}
	}
	lines = append(lines, blockDimStr("loop", loopType))

	if loopType == "for-each" {
		if node.StaticLoopOver != "" {
			lines = append(lines, blockDimStr("over", node.StaticLoopOver))
		}
		if node.StaticLoopAs != "" {
			lines = append(lines, blockDimStr("as", node.StaticLoopAs))
		}
		if len(node.LoopMatches) > 0 {
			lines = append(lines, blockDimStr("matches", fmt.Sprintf("%d", len(node.LoopMatches))))
		}
	} else if node.StaticLoopMax != nil {
		lines = append(lines, blockDimStr("max", fmt.Sprintf("%d", *node.StaticLoopMax)))
	}

	total := loopTotal(node)
	if total > 0 {
		lines = append(lines, blockDimStr("iterations", fmt.Sprintf("%d of %d", node.IterationsCompleted, total)))
	}
	if node.StaticLoopRequireMatches != nil {
		lines = append(lines, blockDimStr("require_matches", boolWord(*node.StaticLoopRequireMatches)))
	}
	if node.BreakTriggered {
		lines = append(lines, blockDimStr("break_triggered", "yes"))
	}

	lines = append(lines, blockCommonModifiers(node)...)

	if node.Status != StatusPending {
		lines = append(lines, blockOutcomeAndDuration(node)...)
	}
	return lines
}

func renderIterationBlock(node *StepNode, indent, width int) []string {
	contentWidth := width - 2*indent
	if contentWidth <= 0 {
		return nil
	}

	glyph := blockTypeGlyph(node.Type)
	sep := renderSeparator(node.ID, glyph, indent, contentWidth)

	lines := []string{sep}
	lines = append(lines, blockDimStr("iteration", itNum(node.IterationIndex)))
	if node.BindingValue != "" {
		lines = append(lines, blockDimStr("value", node.BindingValue))
	}
	if node.Status != StatusPending {
		lines = append(lines, blockOutcomeAndDuration(node)...)
	}
	return lines
}

// ---- Helper builders ---------------------------------------------------------

func blockTypeGlyph(t NodeType) string {
	switch t {
	case NodeShell:
		return "$"
	case NodeHeadlessAgent:
		return "⚙"
	case NodeInteractiveAgent:
		return "❯"
	case NodeSubWorkflow:
		return "↳"
	case NodeLoop:
		return "↺"
	case NodeIteration:
		return "»"
	}
	return "·"
}

func blockDimStr(label, value string) string {
	return tuistyle.LabelStyle.Render(label+": ") + tuistyle.NormalStyle.Render(value)
}

func blockLabelStr(s string) string {
	return tuistyle.SectionStyle.Render(s)
}

func blockCommonModifiers(n *StepNode) []string {
	var lines []string
	if n.CaptureName != "" {
		lines = append(lines, blockDimStr("capture", n.CaptureName))
	}
	if n.StaticCaptureStderr {
		lines = append(lines, blockDimStr("capture_stderr", "yes"))
	}
	if n.StaticContinueOnFailure {
		lines = append(lines, blockDimStr("continue_on_failure", "yes"))
	}
	if n.StaticSkipIf != "" {
		lines = append(lines, blockDimStr("skip_if", n.StaticSkipIf))
	}
	if n.StaticBreakIf != "" {
		lines = append(lines, blockDimStr("break_if", n.StaticBreakIf))
	}
	if n.StaticWorkdir != "" {
		lines = append(lines, blockDimStr("workdir", n.StaticWorkdir))
	}
	return lines
}

func blockExitAndDuration(n *StepNode) []string {
	if n.ExitCode == nil && n.DurationMs == nil {
		return nil
	}
	var lines []string
	lines = append(lines, "")
	failed := n.Status == StatusFailed || (n.ExitCode != nil && *n.ExitCode != 0)
	if n.ExitCode != nil {
		label := "exit"
		val := fmt.Sprintf("%d", *n.ExitCode)
		var exitLine string
		if *n.ExitCode != 0 {
			exitLine = tuistyle.LabelStyle.Render(label+": ") + tuistyle.StatusFailed.Render(val)
		} else {
			exitLine = blockDimStr(label, val)
		}
		if n.DurationMs != nil {
			exitLine += "       " + blockDurationStr(*n.DurationMs, failed)
		}
		lines = append(lines, exitLine)
	} else if n.DurationMs != nil {
		lines = append(lines, blockDurationStr(*n.DurationMs, failed))
	}
	return lines
}

func blockOutcomeAndDuration(n *StepNode) []string {
	var lines []string
	lines = append(lines, "")
	outcome := statusLabel(n.Status)
	failed := n.Status == StatusFailed
	if failed {
		lines = append(lines, tuistyle.LabelStyle.Render("outcome: ")+tuistyle.StatusFailed.Render(outcome))
	} else {
		lines = append(lines, blockDimStr("outcome", outcome))
	}
	if n.DurationMs != nil {
		lines = append(lines, blockDurationStr(*n.DurationMs, failed))
	}
	return lines
}

func blockDurationStr(ms int64, _ bool) string {
	return tuistyle.LabelStyle.Render("duration: ") + tuistyle.NormalStyle.Render(formatDuration(ms))
}

func renderAgentOutput(node *StepNode, contentWidth int, loadedFull bool, pulsePhase float64) []string {
	stdout := sanitizeUTF8(node.Stdout)
	stderr := sanitizeUTF8(node.Stderr)

	var lines []string
	lines = append(lines, "")

	if stdout == "" && stderr == "" {
		if node.Status == StatusInProgress {
			lines = append(lines, blockLabelStr("agent:"))
			for _, line := range tuistyle.SpinnerFrame(pulsePhase) {
				lines = append(lines, tuistyle.AccentStyle.Render(line))
			}
			return lines
		}
		lines = append(lines, tuistyle.LabelStyle.Render("agent: ")+tuistyle.DimStyle.Render("(empty)"))
		return lines
	}

	if stdout != "" && stderr != "" {
		lines = append(lines, blockLabelStr("agent (stdout):"))
		lines = append(lines, renderWrappedOutputLines(stdout, contentWidth, loadedFull)...)
		lines = append(lines, "", blockLabelStr("agent (stderr):"))
		lines = append(lines, renderWrappedOutputLines(stderr, contentWidth, loadedFull)...)
		return lines
	}

	text := stdout
	if text == "" {
		text = stderr
	}
	lines = append(lines, blockLabelStr("agent:"))
	lines = append(lines, renderWrappedOutputLines(text, contentWidth, loadedFull)...)
	return lines
}

// renderOutputSection renders a labeled stdout/stderr block.
func renderOutputSection(label, output string, contentWidth int, loadedFull bool) []string {
	output = sanitizeUTF8(output)
	var lines []string
	lines = append(lines, "")
	if output == "" {
		lines = append(lines, tuistyle.LabelStyle.Render(label+": ")+tuistyle.DimStyle.Render("(empty)"))
		return lines
	}
	lines = append(lines, blockLabelStr(label+":"))
	lines = append(lines, renderWrappedOutputLines(output, contentWidth, loadedFull)...)
	return lines
}

// renderWrappedOutputLines wraps output with truncation if needed.
func renderWrappedOutputLines(output string, contentWidth int, loadedFull bool) []string {
	var t truncatedOutput
	if loadedFull {
		ls := strings.Split(output, "\n")
		t = truncatedOutput{Lines: ls, TotalLines: len(ls)}
	} else {
		t = truncateOutput(output)
	}

	var lines []string
	if banner := t.banner(); banner != "" {
		lines = append(lines, tuistyle.DimStyle.Render(banner))
	}
	w := contentWidth
	if w <= 0 {
		w = 80
	}
	for _, line := range t.Lines {
		sanitized := tuistyle.Sanitize(line)
		if sanitized == "" {
			lines = append(lines, "")
			continue
		}
		for _, wrapped := range wrapLine(sanitized, w) {
			lines = append(lines, tuistyle.NormalStyle.Render(wrapped))
		}
	}
	return lines
}

// renderWrappedText word-wraps text to contentWidth, returning lines.
func renderWrappedText(text string, contentWidth int) []string {
	w := contentWidth
	if w <= 0 {
		w = 80
	}
	var lines []string
	for _, line := range strings.Split(text, "\n") {
		sanitized := tuistyle.Sanitize(line)
		if sanitized == "" {
			lines = append(lines, "")
			continue
		}
		for _, wrapped := range wrapLine(sanitized, w) {
			lines = append(lines, tuistyle.NormalStyle.Render(wrapped))
		}
	}
	return lines
}

// sortedParams returns key: value dim lines for a params map, sorted by key.
func sortedParams(params map[string]string) []string {
	if len(params) == 0 {
		return nil
	}
	keys := make([]string, 0, len(params))
	for k := range params {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	lines := make([]string, 0, len(keys))
	for _, k := range keys {
		lines = append(lines, blockDimStr(k, params[k]))
	}
	return lines
}

func itNum(idx int) string {
	return fmt.Sprintf("%d", idx+1)
}

func loopTotal(n *StepNode) int {
	if len(n.LoopMatches) > 0 {
		return len(n.LoopMatches)
	}
	if n.StaticLoopMax != nil {
		return *n.StaticLoopMax
	}
	return 0
}

// ---- Retained utility functions ----------------------------------------------

func boolWord(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func statusLabel(s NodeStatus) string {
	switch s {
	case StatusSuccess:
		return "success"
	case StatusFailed:
		return "failed"
	case StatusSkipped:
		return "skipped"
	case StatusInProgress:
		return "in progress"
	default:
		return "pending"
	}
}

func formatDuration(ms int64) string {
	if ms < 1000 {
		return fmt.Sprintf("%dms", ms)
	}
	secs := float64(ms) / 1000
	if secs < 60 {
		return fmt.Sprintf("%.1fs", secs)
	}
	totalSecs := int(secs)
	if totalSecs < 3600 {
		mins := totalSecs / 60
		remainSecs := totalSecs % 60
		return fmt.Sprintf("%dm %ds", mins, remainSecs)
	}
	hours := totalSecs / 3600
	mins := (totalSecs % 3600) / 60
	remainSecs := totalSecs % 60
	parts := []string{fmt.Sprintf("%dh", hours)}
	if mins > 0 || remainSecs > 0 {
		parts = append(parts, fmt.Sprintf("%dm", mins))
	}
	if remainSecs > 0 {
		parts = append(parts, fmt.Sprintf("%ds", remainSecs))
	}
	return strings.Join(parts, " ")
}

// fitDetailLine fits one log-pane line into width visible columns. If the
// line already fits, it is returned unchanged (preserving any embedded ANSI
// escapes). If it overflows, styling is stripped and the plain text is
// truncated with an ellipsis.
func fitDetailLine(s string, width int) string {
	if width <= 0 {
		return ""
	}
	if runewidth.StringWidth(tuistyle.Sanitize(s)) <= width {
		return s
	}
	return runewidth.Truncate(tuistyle.Sanitize(s), width, "…")
}

// wrapLine word-wraps s so each returned segment has visual width <= width.
// Words longer than width are rune-split so they still fit.
func wrapLine(s string, width int) []string {
	if width <= 0 {
		return []string{s}
	}
	if runewidth.StringWidth(s) <= width {
		return []string{s}
	}
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{s}
	}
	var out []string
	var cur strings.Builder
	curW := 0
	flush := func() {
		if cur.Len() > 0 {
			out = append(out, cur.String())
			cur.Reset()
			curW = 0
		}
	}
	for _, w := range words {
		ww := runewidth.StringWidth(w)
		if ww > width {
			flush()
			remaining := w
			for runewidth.StringWidth(remaining) > width {
				chunk := runewidth.Truncate(remaining, width, "")
				if chunk == "" {
					_, size := utf8.DecodeRuneInString(remaining)
					if size == 0 {
						break
					}
					chunk = remaining[:size]
				}
				out = append(out, chunk)
				remaining = remaining[len(chunk):]
			}
			if remaining != "" {
				cur.WriteString(remaining)
				curW = runewidth.StringWidth(remaining)
			}
			continue
		}
		if curW == 0 {
			cur.WriteString(w)
			curW = ww
			continue
		}
		if curW+1+ww > width {
			flush()
			cur.WriteString(w)
			curW = ww
			continue
		}
		cur.WriteByte(' ')
		cur.WriteString(w)
		curW += 1 + ww
	}
	flush()
	if len(out) == 0 {
		return []string{s}
	}
	return out
}

// bareWorkflowName strips directory segments and .yaml/.yml suffix from a raw
// workflow reference so fallbacks display "implement-task" rather than
// "workflows/implement-task.yaml".
func bareWorkflowName(s string) string {
	if s == "" {
		return ""
	}
	base := filepath.Base(s)
	ext := filepath.Ext(base)
	if ext == ".yaml" || ext == ".yml" {
		base = strings.TrimSuffix(base, ext)
	}
	return base
}
