#!/usr/bin/env bash
# Copies allowlisted host config from /host-home into the sandbox's writable
# HOME. It keeps mounted credentials read-only, creates private env/zsh files,
# and seeds CLI conveniences such as Codex trust and claude-headless.
set -euo pipefail

HOME_DIR="${HOME:-/workspace/home}"
HOST_HOME_ROOT="${SANDBOX_HOST_HOME_ROOT:-/host-home}"
WORKSPACE_BIN="${SANDBOX_WORKSPACE_BIN:-/workspace/bin}"

mkdir -p \
  "$HOME_DIR/.codex" \
  "$HOME_DIR/.claude" \
  "$HOME_DIR/.config/git"

copy_file_if_present() {
  local source="$1"
  local target="$2"
  if [[ ! -f "$source" ]]; then
    return 0
  fi
  mkdir -p "$(dirname -- "$target")"
  cp "$source" "$target"
  chmod u+rw,go-rwx "$target" 2>/dev/null || chmod u+rw "$target"
}

seed_file_if_present() {
  local source="$1"
  local target="$2"
  if [[ -e "$target" ]]; then
    return 0
  fi
  copy_file_if_present "$source" "$target"
}

trim_space() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

write_sandbox_env_if_present() {
  local source="$HOST_HOME_ROOT/sandbox-secrets.env"
  local target="$HOME_DIR/.sandbox-env"
  local line name value
  if [[ ! -f "$source" ]]; then
    return 0
  fi
  : > "$target"
  chmod u+rw,go-rwx "$target" 2>/dev/null || chmod u+rw "$target"
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="$(trim_space "$line")"
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" == export[[:space:]]* ]]; then
      line="${line#export}"
      line="$(trim_space "$line")"
    fi
    if [[ "$line" != *=* ]]; then
      echo "Invalid sandbox secrets line: expected NAME=value" >&2
      exit 2
    fi
    name="$(trim_space "${line%%=*}")"
    value="${line#*=}"
    if [[ ! "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
      echo "Invalid sandbox secrets variable name: $name" >&2
      exit 2
    fi
    printf 'export %s=%q\n' "$name" "$value" >> "$target"
  done < "$source"
}

write_zshenv() {
  local target="$HOME_DIR/.zshenv"
  {
    printf '%s\n' '# Generated by sandbox-sync-home.sh.'
    printf '%s\n' 'if [[ -r "$HOME/.sandbox-env" ]]; then'
    printf '%s\n' '  source "$HOME/.sandbox-env"'
    printf '%s\n' 'fi'
  } > "$target"
  chmod u+rw,go-rwx "$target" 2>/dev/null || chmod u+rw "$target"
}

ensure_codex_workspace_trust() {
  local config="$HOME_DIR/.codex/config.toml"
  local workspace="/workspace/agent-runner"
  local section="[projects.\"$workspace\"]"
  touch "$config"
  chmod u+rw,go-rwx "$config" 2>/dev/null || chmod u+rw "$config"
  if grep -Fqx "$section" "$config"; then
    return 0
  fi
  {
    printf '\n%s\n' "$section"
    printf '%s\n' 'trust_level = "trusted"'
  } >> "$config"
}

write_claude_headless_helper() {
  local target="$WORKSPACE_BIN/claude-headless"
  mkdir -p "$(dirname -- "$target")"
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' 'set -euo pipefail'
    printf '%s\n' 'if [[ -r "$HOME/.sandbox-env" ]]; then'
    printf '%s\n' '  source "$HOME/.sandbox-env"'
    printf '%s\n' 'fi'
    printf '%s\n' 'exec claude -p "$@"'
  } > "$target"
  chmod 755 "$target"
}

seed_file_if_present "$HOST_HOME_ROOT/codex/auth.json" "$HOME_DIR/.codex/auth.json"
seed_file_if_present "$HOST_HOME_ROOT/codex/config.toml" "$HOME_DIR/.codex/config.toml"

seed_file_if_present "$HOST_HOME_ROOT/claude/.credentials.json" "$HOME_DIR/.claude/.credentials.json"
seed_file_if_present "$HOST_HOME_ROOT/claude/settings.json" "$HOME_DIR/.claude/settings.json"
seed_file_if_present "$HOST_HOME_ROOT/claude/settings.local.json" "$HOME_DIR/.claude/settings.local.json"

copy_file_if_present "$HOST_HOME_ROOT/shell/.zshrc" "$HOME_DIR/.zshrc"
copy_file_if_present "$HOST_HOME_ROOT/shell/.zprofile" "$HOME_DIR/.zprofile"
copy_file_if_present "$HOST_HOME_ROOT/git/.gitconfig" "$HOME_DIR/.gitconfig"
copy_file_if_present "$HOST_HOME_ROOT/git/.gitignore" "$HOME_DIR/.gitignore"
copy_file_if_present "$HOST_HOME_ROOT/git/config-ignore" "$HOME_DIR/.config/git/ignore"

write_sandbox_env_if_present
write_zshenv
ensure_codex_workspace_trust
write_claude_headless_helper
